apiVersion: batch/v1
kind: CronJob
metadata:
  name: scan-node-app-daily
spec:
  schedule: "0 2 * * *"  # tous les jours à 2h du matin
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trivy-scan
            image: aquasec/trivy:latest
            args:
              - image
              - node-app:latest
          restartPolicy: Never
      backoffLimit: 2
