apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sync-admin-credentials
  namespace: default
 
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: admin-credentials
  destination:
    name: admin-credentials
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sync-app-secret
  namespace: default
  
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: app-secret
  destination:
    name: app-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sync-postgres-secret
  namespace: default
  
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: postgres-secret
  destination:
    name: postgres-secret
    create: true
