apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: hcp-vault-connection
  namespace: default
spec:
  address: https://vault-cluster-public-vault-7a8360dc.01151190.z1.hashicorp.cloud:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: hcp-vault-auth
  namespace: default
spec:
  vaultConnectionRef: hcp-vault-connection
  method: kubernetes        # ← Change ici
  mount: kubernetes         # ← Mount habituel pour kubernetes auth
  kubernetes:
    role: default-role       # ← IMPORTANT : le rôle que tu as créé dans Vault
    serviceAccount: default  # ou vault-client si tu en as créé un