---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-credentials
  namespace: default
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBM2LB0skc66jGbDT8ESYOg+f8ipEsxNFvvFM4Kjubhllb12+wR4Zn9zAhW8H9B7WlVjI0X/Uqr2qMiekGYx4S3kPN036s6hWlPxjILxkpvQHJ+DdfOCkKolh8kXuS7RLrJxJLQPXAyhosLDNhO0ESWXX04Aa92CQmLa4Ms69hK24FuqwPBciaq4Pu/lZ/QTqS/bo2GfD29AUDeebrGS1vIWbCyIJHeck17AL9sw9Rf8nlmJxC241ocvYVZla6XnjgA7Jpso73ImjonWqIIXDnP4R5OxfNbPCa+T3we0+Tc87PJmQd4yPzJksFSIAvayCi2NDXAE4CtZUvoQZxmZJLBvY0IgGFwbdcerf61AJpaOVlRdCsJBJjmrXY/zOFnK9RJbmhIEU9SsaYYCBtKofVF/QUEfL3+W/f/8agkQLpsM7z3ILFZUpvIkGTcGyzkC9Ihw+oq3rXNmXEaVDd6FWeMszaIobb6mdJ3FECiObDI4qpDzIHZve0bioNwL6yF3j6US2m04ROXawdSqUZxnQCy+ucV+ZAAAiezrR/CIGbU+jkKAkTLmvT+5uJXaHYL3atgIitmRg1ensIikbH+mQzOMVhkisi/M1DrRNKMQ62GlphYWjhcohxFkFxcS6tta82WhxJZg7oNlL/EIiEhM7UGBsDfOd9ShLjc8uAgOATXk+3HNA7isoRx8Moz3bADt4BeF361reskh51Bi5O8+SQg4zkI3ORAJ9QpgawiSuIW4iWxBAfNB9U6ADPozX7PGsoq6PGRb5ZUP5OsxxM=
  template:
    metadata:
      creationTimestamp: null
      name: admin-credentials
      namespace: default
