---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgA271/GVExJh3cl4tN+/EZTD/0Y8gj7BfwiR5/XAI/044kbHhITIlTOQYMzdB/7Mm96nYL0tK6K41oKyp8IfOPp1cIFMN3rsXcENUvKRkSp4/gx15fg6P0AF4iNR4ZW0o6CBFTnX4Fo0rKWdh5HBMyaWgDVQCNo0ladPknXwthTz+1FcueWbqc3QPY7st4/4t4PKu6vVqdsSb9TY0cjYjYgcdFn1FUG772zbuKvGaiyPi74iAYCfLuAlyCE4OQt2a+R5kfTXWSYuoZjTLJRzu6T/GBjAjYZOlZ43W4vPqc9nphO2PxrBmmGpgEskKzXK90hykaVgDKO7rgQaclVETZhos5fa0CSVRVSC4nSjN+lrwIHwWgfQtL6iCXXOLo5WXi5beFhVF/mXi3+IvR7AJ01fWyXDFTMflfLA4Dv+jKwczNg4joGWT3zMeHGbJH+Y+oxvV6yUBJYWVt8Dpdz+FUlDBZUYeD8w9GKMAKHyiU5piVzrEewyzCEHoDf8nMrXuhRoD+5j0qqX+JSTmk6bhMclY/YSiqjiZOm1KEi/0OyBy2Tcw8St3DMkDPwUhxNil08kGIQkICBXCwYM1TzIItWHGnkLzoGN5Um5bT1LiKAE59it9gHKs6ctftpQBeUYswSS0PyGwntGSkUJwvKe18pqF9emYudNNxHIgo0Y0Ir5DpUZPfQmL1ys4dEGoPKioQowJdAC/V0ol3SJvHTXKHPET8fX3CW9drKLudUKiCRjtTuLuGEDpEDsVoLcHfLGvz6wReS4q1RadF94wBKig==
    SESSION_SECRET: AgCArTjKaFbl+aSAVFD1XshmR1QsIrqEBHE3aXwDI5Ty7Y4kTqsFXxtAPT3h3qhJrMrZ0FNlcnf5IZMLTaZ0HcFAfezK4pFrp8cJ4YWgN9iUMoql0YpksfbvL0y/t3KZOHonxkeV8fGToUd0AVj7HTO3wf+Zkir9/mqdrIiqAPp4GCa2S8j35OAIpdgzNGCzVFF6vX0iPXIxXIQL6IM5g0ZjNGMaX0koqaWioS8iCjx+H5qM7y2ac6MUaCvIYOCBYOrHHrhx6mZb1dGf3XgmJOPE8CyhxelZ3DpIrdiIm60bruu6vddPMFCIUI+cwWJ+YLisx9JUJ4rSKKQVdP+Hib+E7ApoE1MNmnPFcSpkQapJoJvciHrMYi4A2dib49yD+6TcjXXmhuUMW5UfFcxosHBL9ARCAX+JrfOHk1QMkeqOikqPvtnn2oPDX++5pdItNsCt5Tp9QpHhLq3tLjwQKA9fTGZIV2npWEYBM2jVDJCohWW9cmKtAafm3XEfgpICUcJFOyj8TYRts5SG/0QhPEu/y8DQuzh+ZU5udKgJzRb95Cqg+Nqoo6SzWml36Znfb/pn3JhBDNP1whK5Wee/Hx87yELa9Vu9qgoUcQPJL0XNztVv0W1HPjRWUZmTx86ownPdYQjOmDjTf1Fi/cusTMjbt1RHSHFEfPnhncMmsdeYgvlnaaZiPhuaCReYx/80pt/rM30X9Kv7CGWkrF2hO6GHI4F0Ufw=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
