apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: default
  labels:
    app: course-service
    tier: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
        tier: backend
    spec:
      containers:
        - name: course-service
          image: ghcr.io/cyber-pnl/k8sproject/course-service:e39472322dd0fcf3f077079b856cc01f3fce4f20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          envFrom:
            - secretRef:
                name: app-secret
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: s3-secret
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"