apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: default

spec:
  selector:
    app: course-service
  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP
  type: ClusterIP