apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: admin-credentials
  destination:
    name: admin-credentials
    create: true
  refreshAfter: 1h
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: app-secret
  destination:
    name: app-secret
    create: true
  refreshAfter: 1h
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: postgres-secret
  destination:
    name: postgres-secret
    create: true
  refreshAfter: 1h