apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: hcp-vault-connection
  namespace: default
spec:
  address: https://vault-cluster-public-vault-7a8360dc.01151190.z1.hashicorp.cloud:8200
  # caCertSecretRef: ""   # if needed
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: hcp-vault-auth
  namespace: default
spec:
  vaultConnectionRef: hcp-vault-connection
  method: token
  mount: token
  tokenSpec:
    name: vault-token  # Le nom du secret K8s que tu as créé avec ton token hvs...