apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
  namespace: default
 
spec:
  vaultAuthRef: hcp-vault-auth
  mount: admin          # ← le nom de ton KV engine (le préfixe dans /v1/admin/kv → ici "admin")
  type: kv-v2
  path: admin-credentials   # ← ce qui suit /data/ dans ton path
  destination:
    name: admin-credentials   # ← nom du Secret Kubernetes qui sera créé
    create: true
  
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-secret
  namespace: default

spec:
  vaultAuthRef: hcp-vault-auth
  mount: admin          # ← même KV engine que ci-dessus
  type: kv-v2
  path: app-secret      # ← ce qui suit /data/
  destination:
    name: app-secret      # ← nom du Secret Kubernetes qui sera créé
    create: true

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  namespace: default

spec:
  vaultAuthRef: hcp-vault-auth
  mount: admin          # ← même KV engine
  type: kv-v2
  path: postgres-secret     # ← ce qui suit /data/
  destination:
    name: postgres-secret     # ← nom du Secret Kubernetes qui sera créé
    create: true
