apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-credentials
  namespace: default
 
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: /v1/admin/kv/data/admin-credentials
  destination:
    name: admin-credentials
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-secret
  namespace: default
  
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: /v1/admin/kv/data/app-secret
  destination:
    name: app-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  namespace: default
  
spec:
  vaultAuthRef: hcp-vault-auth
  mount: kv              # ← VÉRIFIE ce nom dans Vault UI > Secrets Engines
  type: kv-v2
  path: /v1/admin/kv/data/postgres-secret
  destination:
    name: postgres-secret
    create: true
