apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: hcp-vault-connection
  namespace: default
  annotations:
spec:
  address: https://vault-cluster-public-vault-7a8360dc.01151190.z1.hashicorp.cloud:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: hcp-vault-auth
  namespace: default
spec:
  method: token
  mount: token
  vaultConnectionRef: hcp-vault-connection
  tokenSecretRef:
      name: vault-token
      key: token